[package]
name = "permesh-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde-saphyr.workspace = true
thiserror.workspace = true
permesh-secrets.workspace = true

[dev-dependencies]
tempfile.workspace = true
